### ISSUE TITLE
Add metadata file with render date 

### ISSUE THREAD

**Issue by J535D165** [nicholasmfraser/covid19_preprints#5]
Thanks for your work on this project. Really useful. 

We are working on integrating the preprints into our software. We are facing some challenges with the versioning of this dataset. It would be very helpful to have some (minimal) metadata on the dataset. My suggestion would be to put a small (JSON) metadata file in the data folder that updates with every new version of the dataset. Example:

```
{
  last_update: "2020-06-11",
  url: "https://github.com/nicholasmfraser/covid19_preprints/blob/master/data/covid19_preprints.csv?raw=true"
}
```

What are your thoughts?

**Comment by bmkramer** [comment]
I think the relevant date (for downstream use) should be the date until which the dataset is updated, rather than the render date - or alternatively, include both if the render date is used to check for updates. 

@nicholasmfraser If you agree to this addition, I'm happy to add a few lines to the Rmd file to create it.

**Comment by nicholasmfraser** [comment]
@J535D165 that sounds like a good idea. At the moment there is a weekly release which correspond to the weekly data updates. The date for each new dataset (as @bmkramer notes) is the cut-off point for preprints to be included based on their posting date, rather than the date which I collect the data, which usually follows a few days later. 

@bmkramer that would be great. The data collection for this week is actually running as we speak

**Comment by J535D165** [comment]
>@J535D165 that sounds like a good idea. At the moment there is a weekly release which correspond to the weekly data updates. The date for each new dataset (as @bmkramer notes) is the cut-off point for preprints to be included based on their posting date, rather than the date which I collect the data, which usually follows a few days later.

Oke, I wasn't aware it works like this. This makes it a bit more complicated. Hopefully, we can have the release/render/git commit date in one of the fields :) Such that we can check for new releases automatically. I think `last_update` should be `release_date`, isn't it?

**Comment by bmkramer** [comment]
My suggestion would be to include both `sample_date` and `release_date`, the former to show to end users downstream, the latter to use in automatic detection of updates.

**Comment by bmkramer** [comment]
@nicholasmfraser I've made a PR incorporating these changes

NB: For this week's version, I've kept the original release date (i.e. 2020-06-12)
Future updates will take the system date to set the release date.

**Comment by nicholasmfraser** [comment]
@bmkramer thanks for taking care of this - I've just merged the changes and am starting the new extraction for this week. Will also add a line to the README documenting this.

**Comment by J535D165** [comment]
Thanks!
